# Generated by Django 4.2.8 on 2023-12-21 00:58

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipperName', models.CharField(help_text="sender's name", max_length=50)),
                ('shipperNumber', phonenumber_field.modelfields.PhoneNumberField(help_text="sender's number", max_length=128, region=None)),
                ('shipperemail', models.EmailField(help_text="sender's email", max_length=254)),
                ('receiverName', models.CharField(help_text="receiver's name", max_length=50)),
                ('receiverNumber', phonenumber_field.modelfields.PhoneNumberField(help_text="receiver's number", max_length=128, region=None)),
                ('receiveremail', models.EmailField(help_text="receiver's email", max_length=254)),
                ('waybillNumber', models.UUIDField(default=uuid.uuid4)),
                ('shipment_content', models.CharField(choices=[('cargo', 'cargo'), ('parcel', 'parcel'), ('document', 'document')], max_length=20)),
                ('item_des', models.CharField(help_text='item descriptions', max_length=30)),
            ],
        ),
    ]
