# Generated by Django 4.2.8 on 2023-12-21 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_shippinginfo_est_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'pending'), ('on-hold', 'on-hold'), ('moving', 'moving'), ('cancel', 'cancel'), ('under-inspection', 'under-inspection')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='user',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
