# Generated by Django 4.2.8 on 2023-12-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shippinginfo_id_alter_shippinginfo_waybillnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
