# Generated by Django 4.2.8 on 2023-12-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='weight',
            field=models.IntegerField(default=35),
        ),
    ]
