# Generated by Django 4.2.8 on 2023-12-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shippinginfo_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
