# Generated by Django 4.2.8 on 2023-12-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shippinginfo_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginfo',
            old_name='item_des',
            new_name='item_description',
        ),
    ]
